# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Python application

on:
  push:
    branches: [ "main", "final_staging" ]
  pull_request:
    branches: [ "main", "final_staging"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests/*
        pytest tests/* > tests/test-report.txt
    - uses: actions/upload-artifact@v3
      #if: always()
      with:
        name: test-report
        path: tests/test-report.txt
        retention-days: 30
        
